// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcxdqqk0cp8mN_5hu17rEqW58eSO51w1g',
    appId: '1:810781203404:web:a7358d6102681089a01b69',
    messagingSenderId: '810781203404',
    projectId: 'fing-firebase-cbnu',
    authDomain: 'fing-firebase-cbnu.firebaseapp.com',
    storageBucket: 'fing-firebase-cbnu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAdanlxDsKbVr8_x8znhx8cprMcckG5k0',
    appId: '1:810781203404:android:fcacd3cadc8f7698a01b69',
    messagingSenderId: '810781203404',
    projectId: 'fing-firebase-cbnu',
    storageBucket: 'fing-firebase-cbnu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7YvyASym_MQ20lVkZetNmRKW2lqK0YuE',
    appId: '1:810781203404:ios:7d410791eddf5c4fa01b69',
    messagingSenderId: '810781203404',
    projectId: 'fing-firebase-cbnu',
    storageBucket: 'fing-firebase-cbnu.appspot.com',
    iosClientId:
        '810781203404-s5t9rdab2cdpqfl4sphn4kiplh0nok3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.fing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7YvyASym_MQ20lVkZetNmRKW2lqK0YuE',
    appId: '1:810781203404:ios:7d410791eddf5c4fa01b69',
    messagingSenderId: '810781203404',
    projectId: 'fing-firebase-cbnu',
    storageBucket: 'fing-firebase-cbnu.appspot.com',
    iosClientId:
        '810781203404-s5t9rdab2cdpqfl4sphn4kiplh0nok3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.fing',
  );
}
